# Generated by Django 3.1.7 on 2021-10-03 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilities', '0001_initial'),
        ('accounts', '0001_initial'),
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='members', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='room',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='room',
            name='reports',
            field=models.ManyToManyField(blank=True, to='Utilities.Report'),
        ),
    ]
