# Generated by Django 3.1.7 on 2021-10-04 09:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Rooms', '0002_auto_20211003_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('invite_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invite_for', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Rooms.room')),
            ],
        ),
    ]
