# Generated by Django 3.1.7 on 2021-10-03 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, default='Not provided', max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='Not provided', null=True)),
                ('contact_number', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('gender', models.CharField(blank=True, default='Not provided', max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, default='Not provided', max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('height', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('profile_pic', models.FileField(default='profile_pics/default.png', upload_to='profile_pics/')),
                ('special_info', models.TextField(blank=True, default='No message', null=True)),
            ],
        ),
    ]
