# Generated by Django 3.1.7 on 2021-10-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211013_1458'),
        ('Utilities', '0002_auto_20211004_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uploaded_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
    ]
