# Generated by Django 3.1.7 on 2021-10-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilities', '0003_report_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='D:\\Django-Projects\\medbackend\\media'),
        ),
    ]
